### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by cassiopagnoncelli** [davidhu2000/react-spinners#113]
Just got this bug while trying to install the package with `npm install --save react-spinners`.

I'm using standard React app, nearly brand new generated with `create-react-app`. My log shows

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.11.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'react-spinners',
1 verbose cli   '--save' ]
2 info using npm@6.11.2
3 info using node@v11.11.0
4 verbose npm-session 1d48a16c9ee436b4
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/react-spinners 202ms (from cache)
8 silly pacote tag manifest for react-spinners@latest fetched in 211ms
9 timing stage:loadCurrentTree Completed in 2569ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 26ms
13 silly install loadShrinkwrap
14 timing stage:rollbackFailedOptional Completed in 1ms
15 timing stage:runTopLevelLifecycles Completed in 2656ms
16 silly saveTree conta@0.1.0
17 verbose stack TypeError: Cannot read property 'match' of undefined
17 verbose stack     at tarballToVersion (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:91:20)
17 verbose stack     at inflatableChild (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:103:22)
17 verbose stack     at BB.each (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:59:12)
17 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
17 verbose stack     at Object.gotValue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
17 verbose stack     at Object.gotAccum (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
17 verbose stack     at Object.tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
17 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
17 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
17 verbose stack     at Promise._settlePromiseCtx (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:611:10)
17 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:142:12)
17 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
17 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
17 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
17 verbose stack     at processImmediate (timers.js:637:19)
18 verbose cwd /Users/cassio/src/conta
19 verbose Darwin 18.7.0
20 verbose argv "/usr/local/Cellar/node/11.11.0/bin/node" "/usr/local/bin/npm" "install" "react-spinners" "--save"
21 verbose node v11.11.0
22 verbose npm  v6.11.2
23 error Cannot read property 'match' of undefined
24 verbose exit [ 1, true ]

```

**Comment by MohamedAssaf** [comment]
Hello, Can I take this?

**Comment by davidhu2000** [comment]
@MohamedAssaf any update on this?

**Comment by 0xc0d3r** [comment]
@davidhu2000 I looked into this issue in the below environment and I didn't get any such error.

```
$ node -v
v11.11.0

$npm -v
6.7.0
```

I tested with `yarn` as well but no issues found.

@cassiopagnoncelli Can you confirm this?

**Comment by cassiopagnoncelli** [comment]
➜  conta git:(master) node -v
v13.2.0
➜  conta git:(master) npm -v
6.13.7

**Comment by davidhu2000** [comment]
hmm, wonder if this is related to node somehow.

**Comment by davidhu2000** [comment]
this issue seems related to local setup. so going to close this.
